### ISSUE TITLE
Symbol compration ?

### ISSUE THREAD

**Issue by IanaKhitsko** [Konimiks/euro-diffusion#6]
https://github.com/Konimiks/euro-diffusion/blob/a5e7c1ea61108753826eea62e11d88cb5e094a16/src/index.js#L20

Can we compare just the first char? 
Can you at least combine the conditions ? 

        if (compareChunkToString(chunk, ' '))
            continue;
        if (compareChunkToString(chunk, '\r'))
            continue;

=>
 if (compareChunkToString(chunk, ' ') || compareChunkToString(chunk, '\r'))
            continue;

**Comment by Konimiks** [comment]
combined
